---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: zuul-operator
  labels:
    {{- include "zuul-operator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "zuul-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
