---
apiVersion: v2
name: kube-vip-wrapper
description: "Wrapper chart: kube-vip"
type: application
version: 0.9.2
appVersion: "1.0.1"
dependencies:
  - name: kube-vip
    version: 0.9.5
    repository: "https://kube-vip.github.io/helm-charts/"
