# yamllint disable rule:line-length
docker-registry:
    secrets:
        haSharedSecret: ENC[AES256_GCM,data:IEdjxP2mVu621+bosbRUYQ==,iv:LX1PvPpcJzbY8QPfJniLcFK0eq4rpCHUIHdAy8LkBqw=,tag:BX327JYblf5BH4lYpvSLqw==,type:str]
sops:
    age:
        - recipient: age155k7zzfpc2fpflme9t7tvutulsznh8eqpgv40ldrlu9a5spfks3qld7aav
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWHVGU2dlWmNXTXdJSGZp
            NllTdld1dHVBQUwwR0lkbjF2WE9qYW1RQVVzCmlKQ05IOGVXYzVCTHRubnhGc1Vy
            OTExdWQ1SmlHc1ROZkFrT3lKOG5EY0EKLS0tIGNDWUo1dUdmZG5BWmtMak5Sdnlh
            ekJzQW0zY1BlMXN1MjgvZHI4bmhtZjgK0OasnidwLL0nlEGgUgoI/CRm4o9/fwWb
            1d2hcf6Ps/yNFjOPv/QFXXdTlxCE1dZKS6SX2UpfWldv4phgHO+cMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-21T12:11:03Z"
    mac: ENC[AES256_GCM,data:GyCN6/27I+ujFTkWZ6G1wCTtnmqcUIXbSPPusuCv5UfTIpfS4T/wHUlabaJ9HzmlTxezH7M7ZW0mA7f2u5ndzqNiJwLmktgRQoKVso7FRAQcJSQkaXRFskiEgiIBfLfajb/1F0upE2mxi5oeWBg4qFJh/1qoZleJnXVimRrDchM=,iv:rfBw8QxKpvQvn0Vyy5rGoHAko57q8XjmcmV0D6lICRg=,tag:wgvaPF+qqGKn9onqEvsQeg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
