---
apiVersion: v2
name: cert-manager-wrapper
description: "Wrapper chart: cert-manager"
type: application
version: 1.5.14
appVersion: "1.18.2"
dependencies:
  - name: cert-manager
    version: 1.5.14
    repository: "oci://registry-1.docker.io/bitnamicharts"
