apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ssh.secretName }}
  labels:
    {{- include "opengrok.labels" . | nindent 4 }}
type: Opaque
stringData:
  id_ed25519: |
{{ .Values.ssh.keys.id_ed25519 | indent 4 }}
  id_ed25519.pub: |
{{ index .Values.ssh.keys "id_ed25519.pub" | indent 4 }}
  config: |
    Host review.your.domain 192.168.1.220
      StrictHostKeyChecking no
      UserKnownHostsFile /dev/null
