apiVersion: v2
name: ingress-nginx-wrapper
description: "Wrapper chart: ingress-nginx"
type: application
version: 4.14.1
appVersion: "1.14.1"
dependencies:
  - name: ingress-nginx
    version: 4.14.3
    repository: "https://kubernetes.github.io/ingress-nginx"
