ingress-nginx:
  controller:
    service:
      type: LoadBalancer
      loadBalancerIP: "192.168.1.220"
    ingressClassResource:
      name: nginx
      enabled: true
      default: true
    watchIngressWithoutClass: true
    config:
      allow-snippet-annotations: "true"
      annotations-risk-level: "Critical"
  tcp:
    29418: "gerrit-cluster/gerrit-service:29418"
