---
apiVersion: v2
name: authentik-wrapper
description: "Wrapper chart: authentik"
type: application
version: 2025.10.2
appVersion: "2025.10.2"
dependencies:
  - name: authentik
    version: 2025.12.3
    repository: "https://charts.goauthentik.io"
