# yamllint disable rule:line-length
authentik:
    authentik:
        secret_key: ENC[AES256_GCM,data:x8zfinNJ,iv:umXUPwSZrvTuucO4YTAOMrCmhxG9bnY9dI4JofsumlY=,tag:8gSoi9F+iQGs5TDGbQ0VQQ==,type:str]
        postgresql:
            password: ENC[AES256_GCM,data:2Uj4fLhNuRuR,iv:rK3z2hdJK0q3iehR2vKFRKEFT+eq/MnALoroJgODqCc=,tag:J76I/6gXwQhgnRmZ0IqTyw==,type:str]
        redis:
            password: ""
sops:
    age:
        - recipient: age155k7zzfpc2fpflme9t7tvutulsznh8eqpgv40ldrlu9a5spfks3qld7aav
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqcElWaGE4cXRQbVhXNzZR
            azJNOWJOL1RSdll5bStGQnppT0pzR0UyNHk0Ck5aN1luOTRoVmdNSmg4YU91QVZ0
            WXVNU2tOUFgrc3FRVVFWYW5LeUxZSGcKLS0tIFJDcDJ6dWl6MFY3MGpkVFp4dzFl
            bjFTQmMxOUdMVzhBZDlldzdaVDdjZlUK7dNvpuLdWYqECkxcouVPLO9gve/yemZW
            /JDqdvyB1Ew3kgABOUEYV3BM+ecUhO4vd5lCqKshLBB8wBSNrkQHsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-21T12:08:45Z"
    mac: ENC[AES256_GCM,data:RmZvIXoch2y30Dh1+k3zKhq6Qv0tNO9FKsNyxmeEsTN6kvuE5qVkiWLpQpIT6r9NhOPxli7Q2jQfvdii3EgYxh9Z115rKdKRJ1ProdkVbTQoawWIIspMJbvRBrITX5tE4+ZVSbMQ0LTlrFUzf8ceP9qslX6iobVlm4JV+a0nx6E=,iv:wOm3/x6f9byxF+ljyrro+d6ppJohkZAqvihd6PaHFhY=,tag:HNfeg0U4DcNxM5KIV2WnqQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
