---
apiVersion: v1
kind: Secret
metadata:
  name: ca-key-pair
  labels:
    {{- include "cert-manager-wrapper.labels" . | nindent 4 }}
type: kubernetes.io/tls
stringData:
  tls.crt: |
{{ .Values.ca.crt | indent 4 }}
  tls.key: |
{{ .Values.ca.key | indent 4 }}
