{{- if .Values.createClusterIssuer }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer
  labels:
    {{- include "cert-manager-wrapper.labels" . | nindent 4 }}
spec:
  ca:
    secretName: ca-key-pair # pragma: allowlist secret
{{- end }}
