# yamllint disable rule:line-length
gerrit:
    sshKey: ENC[AES256_GCM,data:5BjHYZ65GffwoZtB89VlZ+NSQm5yhZAlNZoavRMARHpwAUy74tM3o8WAPEh2H/XXWiNLOEnTlyK+ir1x4a6Y2hYO9R6aGwuohyadjK11sKtyEvHrQMJBDESRjAxUEm4q/pQhG7KzkgFUXey4qdBh1uxm7aY0Xf6LSouOVRK3g5tByMWCrvTIg0LHXWaiU9/CTeA6fCIBQZcnwk/P2mrDSAXHQULOInkhDh4iXLbFnH7Do4Y+aCq1xW1hWun2IWQpX4VCsDdiSiqLADtUSi4DaChuYBiHAnn7DZ/hWWUPvu77NAwVKY8K6OeSBzWkdPLuOD9Z28cn4NIW7Z/cwyLfcPJ/vzlb6IHYx7FrzRVoOHzzEynsieCfTfpqEXFIKW8gBNXXJ8rS7Enm3ztbxdejEro0ohrArfYK5rwmrgSUscttuL7qchmRctsOFlulnPmZ+0WEbJMmjAkdARc4RnZhGIJUgUtaHTMxMaHtD7mB8jySnY+8YnSXKFIQTmCVrmrzi/DV+5w4fAAWCviDqOrrJchF5uOT/1F+maTh,iv:/BLXXtfXBjO05GbqZnLh3rJXzTCnsDXO2WG93NJTPvU=,tag:rhbIGpE+Vm6d7pl9dzdHGA==,type:str]
database:
    uri: ENC[AES256_GCM,data:Qy7xWIJePML4rLS8p63RNZJQZjo4isHyLd38HxycKDBBJiMhdu9nNBW7FiUZy+uDVjWAuIQUdps3EchsQw/h5DngFK2xSBjXGXP648QMMrZ7,iv:EMcKcyAuBEKjyBd+c940Ex0uFaxAVMraXUP83brptn8=,tag:LpIGpQ+vjoW/X1godmdjfA==,type:str]
sops:
    age:
        - recipient: age155k7zzfpc2fpflme9t7tvutulsznh8eqpgv40ldrlu9a5spfks3qld7aav
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNWFIvOXQxd0paRjBINE1H
            Z0d2TlArVTc1WHp6TnQ4bmlNK3ZPOE1zQmk4CkJoc3M1RTByMG1lSWdIZ29OeEgv
            RWljVjNtSDdZVmlxYzFoNVNZYndQMjAKLS0tIFI4Sk1rWEhYaXJ1U0ZzdUorRzU5
            ak1rWUlkVjlUb29GRksxcm0xbnlLeUEKeaUKukJw9f3AgrHEUzwEiOAbZ96SsPjI
            chYOKUSc9fSCgZ0vYDgrk5beNqtDmWviIs7AFLWK7zhAkmr7S/JbWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-21T12:30:21Z"
    mac: ENC[AES256_GCM,data:SgJDmywarLjs8mPNrNo8G5qbqfatDSIzbVlv9NICwgXOsMZ/tLXIpmoPjuLNBJz3sgUOU00tUnYsmv4Lb2grVxPrmTCydf2lJumYbaU5QdE5/0+w7EmN1mdDKpqgmLaBMwrkgbQb23lI/9Z6jNl2wkALKBFHdxjd1Nd5bYfAp7M=,iv:T6B10LOOl4Q/8kTwRE0dZMNkm5PXfmilskw95UfnK7g=,tag:i/A5GFi0L6BBm1qGXZ1iyw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
