apiVersion: v2
name: kanboard-wrapper
description: "Wrapper chart: kanboard"
type: application
version: 0.1.0
appVersion: "1.2.50"
dependencies:
  - name: kanboard
    version: 1.2.1
    repository: "https://kube-the-home.github.io/kanboard-helm/"
