# yamllint disable rule:line-length
postgresql:
    global:
        postgresql:
            auth:
                postgresPassword: ENC[AES256_GCM,data:kynCCOQZjC/RQPo=,iv:TheG4d94590bdiczAtb99/YKcI6u2UwOlXNZIRhlE3c=,tag:gOHZ6i/YjmvSHKJUT4I5fQ==,type:str]
                password: ENC[AES256_GCM,data:aYQvFVjC,iv:WmWztwr59fpYICEPXcPiVuMSL3riS3J0kIEU/RJUtww=,tag:fd70zK2EXDOO65o0SOJeOw==,type:str]
sops:
    age:
        - recipient: age155k7zzfpc2fpflme9t7tvutulsznh8eqpgv40ldrlu9a5spfks3qld7aav
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvcDVwODQwMWhsWTQ4Qm1u
            MWVWUTRpTmh1bUI4SS95TjZNSmVnbHRQUUVjCkFJbjNEcjlhTmx1QmgxaUkraDFL
            R2FkaUJ2TEozY0E4cUt1czhpcjdRbVkKLS0tIGtFRDJtOWpUa2VPVjhKSDE0eERM
            cWxYck44cFBaYytiLzNQaXBPS29iUlUKCyl3meUVPekbYyaaH7WwO38tus0zHwgw
            87pH8cabUymeXiFzfCaTQK7fCoiyAyXR19FsnEQkt7+PrOqqQNFIOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-21T12:14:41Z"
    mac: ENC[AES256_GCM,data:kKzm4iYxCDwbo/BLOgPSyJd0XPqbbj3SsBxSD3rpbXZbg/mZWToUoh9m6xSArLkQlNDFvo/XWbRQSE8gaXq58R4hEo56LCxM1MuO6jc84Q2hp5QpjorBGJWJdJOiao0becNfpE+OChrUebvGhWKLPew7ChS1oFjK9UYvBIfhU5s=,iv:9INJbs51TjM8MUCepwTWYTDI+vPalDQwd5171I2wHEc=,tag:4Ri9Kqs71otQHjjFhWOLHA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
