---
postgresql:
  global:
    security:
      allowInsecureImages: true
    defaultStorageClass: "nfs-client"
    postgresql:
      auth:
        username: "ignore"
        database: "ignore"

  primary:
    resources:
      requests:
        memory: 256Mi
        ephemeral-storage: 50Mi
        cpu: 100m
      limits:
        memory: 512Mi
        ephemeral-storage: 2Gi
        cpu: 500m

  image:
    repository: bitnamilegacy/postgresql
