apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: zuul-default-cluster-admin
  labels:
    {{- include "zuul.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: default
    namespace: zuul
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
