apiVersion: v1
kind: Secret
metadata:
  name: creds
  namespace: zuul
  labels:
    {{- include "zuul.labels" . | nindent 4 }}
type: Opaque
stringData:
  # yamllint disable rule:line-length
  dburi: {{ .Values.database.uri }}
  # yamllint enable rule:line-length
---
apiVersion: v1
kind: Secret
metadata:
  name: gerrit-secrets
  namespace: zuul
  labels:
    {{- include "zuul.labels" . | nindent 4 }}
type: Opaque
stringData:
  user: {{ .Values.gerrit.user }}
  sshkey: |
{{ .Values.gerrit.sshKey | indent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: zuul-nodepool-config
  namespace: zuul
  labels:
    {{- include "zuul.labels" . | nindent 4 }}
type: Opaque
stringData:
  nodepool.yaml: |
{{ .Values.zuul.nodepoolConfig | indent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: zuul-tenant-config
  namespace: zuul
  labels:
    {{- include "zuul.labels" . | nindent 4 }}
type: Opaque
stringData:
  main.yaml: |
{{ .Values.zuul.tenantConfig | indent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ssh-zuul-logs
  namespace: zuul
  labels:
    {{- include "zuul.labels" . | nindent 4 }}
type: Opaque
data:
  authorized_keys: {{ .Values.logs.sshPublicKey }}
