---
apiVersion: v1
kind: Secret
metadata:
  name: gerrit-secure-config
  labels:
    {{- include "gerrit.labels" . | nindent 4 }}
data:
  ssh_host_ecdsa_key: {{ .Values.sshHostKeys.private }}
  ssh_host_ecdsa_key.pub: {{ .Values.sshHostKeys.public }}
type: Opaque
