---
apiVersion: v2
name: nfs-subdir-external-provisioner-wrapper
description: |
  nfs-subdir-external-provisioner is an automatic provisioner that
  used your *already configured* NFS server, automatically creating
  Persistent Volumes.
version: 4.0.18
dependencies:
  - name: nfs-subdir-external-provisioner
    version: 4.0.18
    # yamllint disable rule:line-length
    repository: "https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/"
