---
apiVersion: v2
name: redis-wrapper
description: "Wrapper chart: redis"
type: application
version: 24.0.0
appVersion: "8.4.0"
dependencies:
  - name: redis
    version: 25.3.2
    repository: "oci://registry-1.docker.io/bitnamicharts"
