# yamllint disable rule:line-length
redis:
    auth:
        password: ENC[AES256_GCM,data:98G+Xn0x,iv:9eXuWgR7gPeEb0eZi82itjiMFOM19bZaPhwuxvOfeDQ=,tag:GY0BNPc5SclcrcOSh+A9Dg==,type:str]
sops:
    age:
        - recipient: age155k7zzfpc2fpflme9t7tvutulsznh8eqpgv40ldrlu9a5spfks3qld7aav
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXSDZlRHdIS3FUQ1lxdWx3
            eDVMTE16dW5LNUw1OU5MNitwNXRtdjAwZFZvCmdlKzgrZDNCUFY3QXQwWTZMWmZk
            Tk4zVXlURER5aytFUU9aTHpuUnBTNncKLS0tIEpOc2NUcVQ4eUFTZjZ0dkt5NG93
            L09LRzNMc0FVRGtvd2pHcWljN29kNlEKpO0dNCXJ0drqexY64Rp2ss6M5dkuycqH
            Q4fG2qkeUkZDTycs5IvSX+pfcuZroW51VgyTwBA33szDOge6ypkKhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-21T12:09:59Z"
    mac: ENC[AES256_GCM,data:1sxOnD7KmervRrglUuVfsfSvmI9cr3C5+2mzj476+emIGMObcZMeB2OKKLkCKqgaTStonv+jxb67zQMtGpQs/nkQgPBcdofZoUcbov9wbDZ9G2RBFhYOrQSy+S8NcU8L41PUsy2UI0j6V293z7qaN3fQPuMYsWNtDxN80R/f6yI=,iv:rMyLmCyxLPq1yIlvImCBUHCGprOHaTno4xgdxwAozTU=,tag:dEmG4aDxu18r36lKLwm+zQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
