# yamllint disable rule:line-length
env:
    CMD_DB_URL: postgres://mockhedgedoc:mockhedgedoc@postgresql.postgres.svc.cluster.local:5432/mockhedgedocdb
    CMD_SESSION_SECRET: mock-string
    CMD_OAUTH2_CLIENT_SECRET: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
