# yamllint disable rule:line-length
env:
    CMD_DB_URL: ENC[AES256_GCM,data:mMq9i8mBh3cnAGu7TTW59MnPDzt/sSd8vedWnHtua5vfu4ar0EhwkniaWHEMuWw8t2RQWbvHRpB1SOp9o5Jrcyn0gjdFnlbQ5NxekUCQacrFTQ==,iv:FrbXlaQ0wc3NbUYC/hJp0IhKyKkyqomWy7bCbk5YqGo=,tag:+HLPpx27MRDJZ3qWODssgw==,type:str]
    CMD_SESSION_SECRET: ENC[AES256_GCM,data:Uk0573J2IlcT+ofACv72/dsg2cj9gwcooqoG8kMuoR4cMjXs37L5k5Q=,iv:GGH++zLLUyE4RyLz9PylumjCSUo1fZTU0Eu7bKGiPLs=,tag:1NAkBv6HcmKAz7rsdNIQ9w==,type:str]
    CMD_OAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:nMV8sAC5SKUxcldOEdL6KPy27s//X/kgIOF6eW3peP085ANzZh5ungYZobW2OYVlKn5tK/OC/ZIS6WHUBKO/urtagBBMG120C+Piek49X91Kw4cqOzoQU4E/U6H7YCZKw+UVVbmrZnTXbXYdM4ypApH7g57yKy63P27haJRlSuA=,iv:HxMhAwJFhBTIzXIonbs/orxrOgI3dZ/ck6GO1cOUJYw=,tag:OpPbLLMinwbjlVbdnftjUw==,type:str]
sops:
    age:
        - recipient: age155k7zzfpc2fpflme9t7tvutulsznh8eqpgv40ldrlu9a5spfks3qld7aav
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTm4vbVFGNDVsT01TekRC
            aFFIYUx6QXZaUTNncUJPWnNWTnoyRDVnVGxJCjEvbXZxV3pyMGF2QnBZQW1HZHB3
            QWJ5OVJsMUp2dmN4TldDREFOdVdFdnMKLS0tIE9SWGFudHBFUUx4SEcrbG9qWlJD
            LytlZjNpR0x0d3pSUFdrN2NGaDB4bW8Ky69qoInNwL4VnDHN69ESGUtLDgM+AYDd
            QWIOSElPlR/xNTftBSVOz/0gvwyYmKIgUFVa5WfeE6ewtWBZUsViSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-21T12:13:32Z"
    mac: ENC[AES256_GCM,data:UHhOE/Ug7uykluEJoxOo8U6qHYbfzuGmjahL6NFTuRhttT1d8q/slXLZVhEQWfGstBwa/Z0GKOn046Wun9QRl+vO6Yuco4ViBauq9AimXjuEgkTcXz/hQjORqLW+fsPwG/SMoGzB1TeQDtWPu5iacnG70Op6ksTBz4L3gycT0cQ=,iv:7T8COlVI0FPqyp52CGEMOR2P3K/bR1M4k0cEOUwSRok=,tag:0MnQLeZnIAj2ufV0tiOzRw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
