---
image:
  repository: quay.io/hedgedoc/hedgedoc
  tag: "1.10.0"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: hedgedoc.your.domain
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: hedgedoc-tls # pragma: allowlist secret
      hosts:
        - hedgedoc.your.domain

env:
  # Basic configuration
  CMD_DOMAIN: "hedgedoc.your.domain"
  CMD_URL_ADDPORT: "false"
  CMD_PROTOCOL_USESSL: "true"

  # Upload configuration
  CMD_ALLOW_FREEURL: "true"
  CMD_ALLOW_ANONYMOUS: "false"
  CMD_ALLOW_ANONYMOUS_EDITS: "false"

  # OAuth2 / Authentik configuration
  # You need to create an OAuth2/OpenID provider in Authentik first
  CMD_OAUTH2_PROVIDERNAME: "Authentik"
  CMD_OAUTH2_CLIENT_ID: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
  CMD_OAUTH2_AUTHORIZATION_URL: >-
    https://sso.your.domain/application/o/authorize/
  CMD_OAUTH2_TOKEN_URL: >-
    http://authentik-server.authentik.svc.cluster.local/application/o/token/
  CMD_OAUTH2_USER_PROFILE_URL: >-
    http://authentik-server.authentik.svc.cluster.local/application/o/userinfo/
  CMD_OAUTH2_USER_PROFILE_USERNAME_ATTR: "preferred_username"
  CMD_OAUTH2_USER_PROFILE_DISPLAY_NAME_ATTR: "name"
  CMD_OAUTH2_USER_PROFILE_EMAIL_ATTR: "email"
  CMD_OAUTH2_SCOPE: "openid profile email"

persistence:
  enabled: true
  storageClass: "nfs-client"
  accessMode: ReadWriteOnce
  size: 2Gi
  mountPath: /hedgedoc/public/uploads

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 256Mi
