# yamllint disable rule:line-length
ssh:
    secretName: ENC[AES256_GCM,data:+M/WhcTEHgWq8bA8,iv:Xa/BvW0yq8GPv0rqMWBECMdRHeed5gKdRqSPBejQHXU=,tag:f4bbKD1/8XbGH5TKaljCPQ==,type:str]
    keys:
        id_ed25519: ENC[AES256_GCM,data:71lzECulTBeaqh824pSxUrDAAauTwSBPc6qsvXyFjE/Ia+5+Z1qc/FXMZIZ3GA2lofeikub89hnF6Nc/6z3BiffJJD7hGxTc5dNyYJWMpEPuddl8mreRrn80FLzr/xAqe1L5iQmIVUPb7XRyhUNpiCdHdAl0YjzoF1z74BSfFwhLw/T2/Ixi4ctmKeMo6/JBgRcBTDEwhp8aDQLZBpgFixDyWZPP1JD2RizJnL9d8c4232Y6Tl24b7+Fhjcrm+qpeEXxzRkTa130tm5OOas4/7YeuMU/Rn4QK5EkukMsf3v9YBRObHO3sLyiS17n3hcFvtUYwV/carxGnJoIiqa51vtszIeBb3xpHe951wh2WKiLEouEjZbX4b0ZN9i4OnxYkaqk0HpYNE1JlRzQ8dplRBkWvioCFaqhvWjUI1Hz61mBnyBk3gj6iqNjjodfWQu3DDYFF0z6HHICe7xGHRVK3pEXDFgqyGtv+TxKe+Pi89U8V6VN0G3CmyqkMPGjAh0+t4BDAYBcHxJMXchBz9Ks,iv:OUts+T/B6ruC2m18HsCFDj3ccspfkYQgWrD1F97EdOg=,tag:nouVt4hDMnOyPbYtSfgs8w==,type:str]
        id_ed25519.pub: ENC[AES256_GCM,data:asChqSZ01mMvnUkS9NJGGVod4gtCTOHrEKFVzzu3W6aTYt0Ye5Vmuf12wdeksAA5O/wgzhb3ZbKgSkkGROki++Q8vaWh8vWjsFpCnvtTl12XFTVgNBRSq/f+vWNI,iv:DAqfAXvidB2kRgLQqXDw0u0dlFB0mqT5kNdjVjug6Gg=,tag:VQjMp9MnLb6bTbSgLRsXlg==,type:str]
sops:
    age:
        - recipient: age155k7zzfpc2fpflme9t7tvutulsznh8eqpgv40ldrlu9a5spfks3qld7aav
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bFJHOTM0SzNMa0hEUHUv
            citjSzgwN2tZT2tnZmQ5RXlqcTZJNHZaNXk0CmZQZ21YejNCWnlrTHg2NU9wc3Nm
            SmoxUGVHdHB3VmxBQjU1blQ5QzhGRkEKLS0tICs4UG5CU2lqblpLYWhOUHpzZ3Fj
            VWlDZjVJYVdkZ3BEOHNpOG5qalhGVzgKKoQNzG+4dC3nDVVy5SguRq2wcqgYnodO
            NX/OzeOHnWNRQz8ZQvfmbbnsXpJHtX8LfH4yN4/OU1i3zajMAggo4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-21T11:46:32Z"
    mac: ENC[AES256_GCM,data:P67qx0YAU/eBmM+NSJD3+MB1OnWakt/nkKqaxUp7NCZ6Lz5+lpMB8Dt4eSBtE0Tu9t6YkijrnK3ta3AYxU8GLJvJGKx34lThEkGsiR3zXwwRvXekU7pGMN4UA8xjYwELnh9yJ48p+VCXNdZW5/mko1hbRJ7W+Svvp+v4P8FQhQ8=,iv:1Z5HzGET11qBwGhCelSTnjbZvxJK/4QNysm+sCdxCMw=,tag:4Ogf03jnuwkbnOY/PWwMEg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
