---
apiVersion: v2
name: gerrit-operator-wrapper
description: |
  This helm chart creates a Deployment for the gerrit-operator. A corresponding
  Service for the operator is implicitly created.
type: application
version: 0.1.0
dependencies:
  - name: gerrit-operator
    version: 0.1.0
    repository: "file://../vendor/gerrit-operator"
  - name: gerrit-operator-crds
    version: 0.1.0
    repository: "file://../vendor/gerrit-operator-crds"
    condition: installCRDs
