apiVersion: v2
name: miniflux-wrapper
description: "Wrapper chart: miniflux"
type: application
version: 0.1.0
appVersion: "2.2.5"
dependencies:
  - name: miniflux
    version: 0.9.2
    repository: "https://charts.gabe565.com"
