# yamllint disable rule:line-length
miniflux:
    env:
        DATABASE_URL: ENC[AES256_GCM,data:99gL4qnxycGOsWMQURe39hLG5RS5myc5lM/iPVf8yepiQQFSnVomUPwVuIoRp0oHwWHC+9HqUDPCI1MtdguHOM/N5UIm9kIViNoDtg2MVWIs9aofoNI8StlRqUs6tSVJ0KQ=,iv:G/MXp71cJbGekZEWG5x8Og/1sxcbfSEbLZHYrV0cLqY=,tag:HpxjpjqUnLgGGzblmIs1Ng==,type:str]
        ADMIN_USERNAME: ENC[AES256_GCM,data:Ae+pYhU=,iv:FzVSMjofSomS/aiwpk776TTlSF6/fQ9+931d1UvuC+s=,tag:04/HZz4EDg784JOHMwm2Wg==,type:str]
        ADMIN_PASSWORD: ENC[AES256_GCM,data:1BOna7hjCwA=,iv:vZuH5Kh/R13p5KSUzDwmQrXb0c1XfxFUHbZ/tNXhGrI=,tag:oCpigAakmC0/GDLdv1rO9Q==,type:str]
sops:
    age:
        - recipient: age155k7zzfpc2fpflme9t7tvutulsznh8eqpgv40ldrlu9a5spfks3qld7aav
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwQmZyalVYaExtcTg0N0hj
            a295WDNHSkt1WERZenJkYXN0ZDE3bEZXV0RBCjNLSEtwN2xESnhKeFhTU005VGJy
            V09qZ3dJWkxTSGlyR3d5dzZSSEFWV0EKLS0tIHpvaXJvTWhocXppejhHUEwrZHFm
            WHBJbEdOalBMQlVpbFV6YXY5NmUxMVkKhsIiOHXOaK2jY+AxU98eDZcyUTQrPpJO
            qcgFNknSGwhlCZbs0z0pKpIfFWA/794J2mVi4LR6S5m7dIX8JSEaMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T21:37:34Z"
    mac: ENC[AES256_GCM,data:rGg4GRDoFQhO3f5kOmTu8O4phZy57kNYga50jWOYlkrzGavrtCMMovkaXiGcofnfksrIchZDTyCOT9GOuNqwWtjjVedh6FZrrCpMtmg9tM6G7eETKUVUqhfXdQ4LrRGMUNuvxC7jW8RG5hjyAHk5yGgAav7FFYaMvPdCU08RP0A=,iv:XWdWjtJ5wlMZfTZG2toSxOXmY+tHTsw3g3IpRsv+/V8=,tag:xoaB5egZTOpKMC1NAuvjtg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
