# yamllint disable rule:line-length
miniflux:
    env:
        DATABASE_URL: postgres://mockuser:mockpass@postgresql.postgres.svc.cluster.local:5432/mockdb?sslmode=disable
        ADMIN_USERNAME: mockadmin
        ADMIN_PASSWORD: mockpassword
